[tool.poetry]
name = "jupyter-llm"
version = "1.1.4"
description = ""
authors = ["Matthew Printz <matt@jataware.com>"]
license = "MIT"
readme = "README.md"
# packages = [{include = "jupyter_llm"}]

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.6.3"
jupyterlab-server = "^2.22.1"
pandas = "^2.0.1"
matplotlib = "^3.7.1"
xarray = "^2023.4.2"
numpy = "^1.24.3"
archytas = "^1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
